#!bin/bash -v

wget https://install.service-now.com/glide/distribution/builds/package/app-signed/mid/2023/09/14/mid.utah-12-21-2022__patch7-09-07-2023_09-14-2023_1002.linux.x86-64.zip
sudo mkdir ~/mid/ ; cd ~/mid/ ; sudo unzip ../mid.utah-12-21-2022__patch7-09-07-2023_09-14-2023_1002.linux.x86-64.zip 
sudo sed -i 's/#wrapper.java.command=jre\/bin\/java/wrapper.java.command=\/usr\/bin\/java/' /home/makefarm/mid/agent/conf/wrapper-override.conf
cd ~/mid/agent; sudo ./installer.sh -silent -INSTANCE_URL https://makenow.service-now.com/ -MUTUAL_AUTH N -MID_USERNAME makenow_mid_temp -MID_PASSWORD ServiceNow1! -USE_PROXY N -APP_NAME $1 -MID_NAME $2 -APP_LONG_NAME $3 -CERTIFICATE_REVOCATION N -NON_ROOT_USER makefarm
rm ~/mid.utah-12-21-2022__patch7-09-07-2023_09-14-2023_1002.linux.x86-64.zip
